AUTH0_DOMAIN        = "dev-7zqyj7kw67uj37v3.us.auth0.com"   # from Auth0 dashboard → Settings → Domain
AUTH0_CLIENT_ID     = "QNt39s828v83kxxGaplMFBIjTFXP8c3H"          # from Auth0 dashboard → Settings → Client ID
AUTH0_CLIENT_SECRET = "W-B4Yh7UD27-MMeIsW82C1jzJjAGFoTAfUSqrS--JEYYOl-E5wuFw2fjKE7y9cAw"      # from Auth0 dashboard → Settings → Client Secret
AUTH0_CALLBACK      = "http://localhost:8501"         # must match Allowed Callback URLs in Auth0
BACKEND_URL         = "http://localhost:8000"         # FastAPI backend